server:
  port: 8001
spring:
  sql:
    init:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: aishu123
    url: jdbc:postgresql://localhost:5433/gasgodb
    username: aishu
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
    show-sql: true